### ISSUE TITLE
Can't start.

### ISSUE THREAD

**Issue by brutevinch** [htreu/OpenHAB-HomeKit-Bridge#23]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--server',
1 verbose cli   '127.0.0.1:8080',
1 verbose cli   '--sitemap',
1 verbose cli   'homekit',
1 verbose cli   '--pincode',
1 verbose cli   '13572460' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart openHAB-HomeKit-Bridge@1.1.0
6 info start openHAB-HomeKit-Bridge@1.1.0
7 verbose unsafe-perm in lifecycle true
8 info openHAB-HomeKit-Bridge@1.1.0 Failed to exec start script
9 verbose stack Error: openHAB-HomeKit-Bridge@1.1.0 start: `node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid openHAB-HomeKit-Bridge@1.1.0
11 verbose cwd /opt/Sources/OpenHAB-HomeKit-Bridge
12 error Linux 4.1.6-v7+
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"
14 error node v0.12.6
15 error npm  v2.11.2
16 error code ELIFECYCLE
17 error openHAB-HomeKit-Bridge@1.1.0 start: `node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"`
17 error Exit status 1
18 error Failed at the openHAB-HomeKit-Bridge@1.1.0 start script 'node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"'.
18 error This is most likely a problem with the openHAB-HomeKit-Bridge package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"
18 error You can get their info via:
18 error     npm owner ls openHAB-HomeKit-Bridge
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ryanborstelmann** [comment]
Did you ever figure this issue out? Running into the same exact problem.

**Comment by yozik04** [comment]
And if you try ```node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"``` directly? What do you see?

**Comment by rcbosman** [comment]
I'm getting the following error:
pi@raspberrypi:/usr/share/openhab/extra/homekit/lib $ node index.js "--server" "127.0.0.1:8080" "--sitemap" "homekit" "--pincode" "13572460"
/usr/share/openhab/extra/homekit/lib/index.js:2
import { startOpenHABBridge } from './openHABBridge.js';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by kstaniek** [comment]
I'm getting the same issue. Any fix?

**Comment by cyb3rt0m** [comment]
Has anyone found a fix to this issue? Seems to persist in the latest code base.
