### ISSUE TITLE
Startup Error - TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by Tscherno** [htreu/OpenHAB-HomeKit-Bridge#27]
npm@2.14.7 /usr/lib/node_modules/npm

> node index.js start "--server" "cubox-i.fritz.box:80" "--sitemap" "homekit"
/srv/openhab/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:25
        if (!widget.item) {
                   ^

TypeError: Cannot read property 'item' of undefined
    at SitemapParser.parseSitemap (SitemapParser.js:13:18)
    at openHABBridge.js:36:37
    at Request._callback (RestClient.js:15:11)
    at Request.self.callback (/srv/openhab/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/srv/openhab/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/srv/openhab/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:962:12)

Sitemap:
sitemap homekit label="HomeKit" {
  # On/Off Item (lights, outlets)
  Switch item=Light_FF_Office_Ceiling label="Licht"
}

**Comment by htreu** [comment]
please provide the output of the sitemap from openHABs REST interface. Paste this URL into the browser and let me know the output:

http://cubox-i.fritz.box:80/rest/sitemaps/homekit

**Comment by htreu** [comment]
This should be fixed by 6b1cb68c12674c29fcde0925737a43ec73fe09f1.
