### ISSUE TITLE
Crashes on Pi Respbian Jessie

### ISSUE THREAD

**Issue by ozobken** [htreu/OpenHAB-HomeKit-Bridge#55]
I'm getting a crash soon after start:

raspberrypi:ken 357> npm start -- --name "myOpenHAB-Bridge" --server 127.0.0.1:8080 --sitemap demo

> openHAB-HomeKit-Bridge@1.3.3 start /home/ken/openhab/OpenHAB-HomeKit-Bridge-master
> node index.js start "--name" "myOpenHAB-Bridge" "--server" "127.0.0.1:8080" "--sitemap" "demo"

/home/ken/openhab/OpenHAB-HomeKit-Bridge-master/node_modules/babel-core/node_modules/babel-traverse/lib/scope/index.js:59
function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key i
                                                                                                                                           ^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/ken/openhab/OpenHAB-HomeKit-Bridge-master/node_modules/babel-core/node_modules/babel-traverse/lib/path/index.js:33:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

npm ERR! Linux 4.1.17+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--name" "myOpenHAB-Bridge" "--server" "127.0.0.1:8080" "--sitemap" "demo"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! openHAB-HomeKit-Bridge@1.3.3 start: `node index.js start "--name" "myOpenHAB-Bridge" "--server" "127.0.0.1:8080" "--sitemap" "demo"`
npm ERR! Exit status 1

I've tried node 4.0.0 as well, with identical results - The standard install of node on Jessie is 0.10, so it doesn't meet the base requirements.

I'm using and arm6 build of node from:

wget https://nodejs.org/dist/v4.1.2/node-v4.1.2-linux-armv6l.tar.gz

**Comment by ozobken** [comment]
I've moved on to the openhab2/homekit inbuilt
