### ISSUE TITLE
TypeError in SitemapParser

### ISSUE THREAD

**Issue by cyb3rt0m** [htreu/OpenHAB-HomeKit-Bridge#62]
Has anyone run into the following:

```
# npm -v
2.15.11
# node -v
v4.7.2
# npm start -- --name "myOpenHAB-Bridge" --server x.x.x.x:xxxx --sitemap somerset

Starting the bridge myOpenHAB-Bridge ...
/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:98
      return widget.type === 'Frame' && (widget.icon === 'outlet' || widget.label === 'outlet');

                   ^

TypeError: Cannot read property 'type' of undefined
    at SitemapParser.looksLikeOutletFrame (/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:76:12)
    at SitemapParser.parseSitemap (/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:30:16)
    at /opt/OpenHAB-HomeKit-Bridge/lib/openHABBridge.js:59:39
    at Request._callback (/opt/OpenHAB-HomeKit-Bridge/lib/RestClient.js:31:11)
    at Request.self.callback (/opt/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

```

**Comment by cyb3rt0m** [comment]
I've managed to get past this error by hard coding the return value of looksLikeOutletFrame() but now hitting more type error issues:

```
Starting the bridge myOpenHAB-Bridge ...
/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:98
      return widget.type === 'Frame' && (widget.icon === 'outlet' || widget.label === 'outlet');
                   ^

TypeError: Cannot read property 'type' of undefined
    at SitemapParser.looksLikeOutletFrame (/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:76:12)
    at SitemapParser.parseSitemap (/opt/OpenHAB-HomeKit-Bridge/lib/SitemapParser.js:30:16)
    at /opt/OpenHAB-HomeKit-Bridge/lib/openHABBridge.js:59:39
    at Request._callback (/opt/OpenHAB-HomeKit-Bridge/lib/RestClient.js:31:11)
    at Request.self.callback (/opt/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/OpenHAB-HomeKit-Bridge/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)

```
